<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Tester-PC" failures="3" tests="31" name="FeesManager" time="72.862" errors="0" timestamp="17 Aug 2018 05:46:02 GMT">
  <testcase classname="com.mytest.FeesManager" name="Add_Admission" time="24.314"/>
  <testcase classname="com.mytest.FeesManager" name="Blank_Now_Receiving_Field" time="7.617"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_aplhabets" time="0.392"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_special_characters" time="0.404">
    <failure type="java.lang.AssertionError" message="Now Receiving field contain alphabets expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Now Receiving field contain alphabets expected [true] but found [false]
at com.mytest.FeesManager.Now_Receiving_contains_special_characters(FeesManager.java:105)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Now_Receiving_contains_special_characters -->
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_whitespaces" time="0.396"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_whitespaces_at_begining" time="0.286"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_numbers" time="0.283"/>
  <testcase classname="com.mytest.FeesManager" name="Payment_Mode_Functionality" time="0.18"/>
  <testcase classname="com.mytest.FeesManager" name="Blank_NextdueDate_functionality" time="0.233"/>
  <testcase classname="com.mytest.FeesManager" name="NextdueDate_functionality" time="3.749"/>
  <testcase classname="com.mytest.FeesManager" name="Notes" time="0.246"/>
  <testcase classname="com.mytest.FeesManager" name="Payment_Clear" time="0.203"/>
  <testcase classname="com.mytest.FeesManager" name="Save_Changes_button_functionality" time="2.146"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Payment_Fee_Status_functionality" time="0.429"/>
  <testcase classname="com.mytest.FeesManager" name="View_Receipts_functionality" time="1.795"/>
  <testcase classname="com.mytest.FeesManager" name="Update_Fee_Receipt" time="4.783"/>
  <testcase classname="com.mytest.FeesManager" name="Blank_Fee_Refund" time="3.341"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_aplhabets" time="0.174"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_special_characters" time="0.411">
    <failure type="java.lang.AssertionError" message="Fee Refund field contain alphabets expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Fee Refund field contain alphabets expected [true] but found [false]
at com.mytest.FeesManager.Fee_Refund_contains_special_characters(FeesManager.java:302)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Fee_Refund_contains_special_characters -->
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_whitespaces" time="0.204"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_whitespaces_at_begining" time="0.209"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_lessthan_Paid_Fees" time="1.28"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_numbers" time="0.161"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Payment_Mode_Functionality" time="0.141"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Notes" time="0.194"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Payment_Clear" time="0.163"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Save_Changes_button_functionality" time="2.105"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Fee_Status_functionality" time="0.382">
    <failure type="java.lang.AssertionError" message="Due Date NOT Getting Saved expected [10/10/2018] but found [NA]">
      <![CDATA[java.lang.AssertionError: Due Date NOT Getting Saved expected [10/10/2018] but found [NA]
at com.mytest.FeesManager.Fee_Refund_Fee_Status_functionality(FeesManager.java:400)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Fee_Refund_Fee_Status_functionality -->
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_View_Receipts" time="1.489"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Update_Fee_Receipt" time="6.36"/>
  <testcase classname="com.mytest.FeesManager" name="Delete_Fee_Receipt" time="8.686"/>
  <testcase classname="com.mytest.Login" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="com.mytest.FeesManager" name="Fee_Manager_Online" time="0.0">
    <ignored/>
  </testcase> <!-- Fee_Manager_Online -->
</testsuite> <!-- FeesManager -->
