<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Tester-PC" failures="6" tests="32" name="Receipt" time="61.615" errors="0" timestamp="10 Aug 2018 10:45:43 GMT">
  <testcase classname="com.mytest.Receipt" name="Add_Account_Head" time="11.268"/>
  <testcase classname="com.mytest.Receipt" name="Name_contain_Special_Characters" time="3.725">
    <failure type="java.lang.AssertionError" message=" Name Contains Special Characters expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Name Contains Special Characters expected [true] but found [false]
at com.mytest.Receipt.Name_contain_Special_Characters(Receipt.java:48)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Name_contain_Special_Characters -->
  <testcase classname="com.mytest.Receipt" name="Name_contain_numbers" time="0.209"/>
  <testcase classname="com.mytest.Receipt" name="Name_contain_whitespaces" time="0.32"/>
  <testcase classname="com.mytest.Receipt" name="Name_contain_alphabets" time="0.208"/>
  <testcase classname="com.mytest.Receipt" name="Name_field_is_Blank" time="2.427"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_special_characters" time="0.573">
    <failure type="java.lang.AssertionError" message=" Mobile No Contains Spaecial Characters expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Mobile No Contains Spaecial Characters expected [true] but found [false]
at com.mytest.Receipt.Mobile_No_contain_special_characters(Receipt.java:97)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Mobile_No_contain_special_characters -->
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_numbers" time="0.289"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_whitespaces" time="0.32"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_alphabets" time="0.166"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_whitespaces_at_begining" time="0.324"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_field_is_Blank" time="0.071"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_lessthan_10_numbers" time="0.166">
    <failure type="java.lang.AssertionError" message=" Mobile No Contains Less than 10 numbers expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Mobile No Contains Less than 10 numbers expected [true] but found [false]
at com.mytest.Receipt.Mobile_No_contain_lessthan_10_numbers(Receipt.java:159)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Mobile_No_contain_lessthan_10_numbers -->
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_greaterthan_10_numbers" time="0.285"/>
  <testcase classname="com.mytest.Receipt" name="Email_contains_whitespaces" time="2.624"/>
  <testcase classname="com.mytest.Receipt" name="Email_valid" time="0.384"/>
  <testcase classname="com.mytest.Receipt" name="Email_contains_whitespaces_at_begining" time="1.589">
    <failure type="java.lang.AssertionError" message=" Email contain Whitespaces at Begining expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Email contain Whitespaces at Begining expected [true] but found [false]
at com.mytest.Receipt.Email_contains_whitespaces_at_begining(Receipt.java:202)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Email_contains_whitespaces_at_begining -->
  <testcase classname="com.mytest.Receipt" name="Amount_field_is_Blank" time="0.095"/>
  <testcase classname="com.mytest.Receipt" name="Amount_contain_special_characters" time="0.388">
    <failure type="java.lang.AssertionError" message="Amount Contains Spaecial Characters expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Amount Contains Spaecial Characters expected [true] but found [false]
at com.mytest.Receipt.Amount_contain_special_characters(Receipt.java:220)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Amount_contain_special_characters -->
  <testcase classname="com.mytest.Receipt" name="Amount_contain_whitespaces" time="0.259"/>
  <testcase classname="com.mytest.Receipt" name="Amount_contain_alphabets" time="0.191"/>
  <testcase classname="com.mytest.Receipt" name="Amount_contain_numbers" time="0.203"/>
  <testcase classname="com.mytest.Receipt" name="Amount_contain_negative_numbers" time="0.194"/>
  <testcase classname="com.mytest.Receipt" name="Amount_contain_whitespaces_at_begining" time="0.185"/>
  <testcase classname="com.mytest.Receipt" name="Payment_Mode_Functionality" time="0.132"/>
  <testcase classname="com.mytest.Receipt" name="Account_Head" time="0.222"/>
  <testcase classname="com.mytest.Receipt" name="Notes" time="0.227"/>
  <testcase classname="com.mytest.Receipt" name="Save_Changes_Button_Functionality" time="2.186"/>
  <testcase classname="com.mytest.Receipt" name="Update_Functionality" time="8.727"/>
  <testcase classname="com.mytest.Receipt" name="Delete" time="5.488">
    <failure type="java.lang.AssertionError" message="Receipt NOT Getting Deleted expected [No data available in table] but found [4]">
      <![CDATA[java.lang.AssertionError: Receipt NOT Getting Deleted expected [No data available in table] but found [4]
at com.mytest.Receipt.Delete(Receipt.java:369)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Delete -->
  <testcase classname="com.mytest.Receipt" name="Cheque_Payment_Mode" time="7.786"/>
  <testcase classname="com.mytest.Receipt" name="Online_Payment_Mode" time="10.295"/>
  <testcase classname="com.mytest.Receipt" name="Mobile_No_contain_negative_numbers" time="0.0">
    <ignored/>
  </testcase> <!-- Mobile_No_contain_negative_numbers -->
  <testcase classname="com.mytest.Login" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
</testsuite> <!-- Receipt -->
